services:
  postgres:
    image: blog_db_image
    container_name: blog_db_container
    restart: always
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - blog_data:/var/lib/postgresql/data

volumes:
  blog_data: